package fr.exodeus.zombies.Objects.Entity.Render.Model;
//Date: 02/03/2015 20:13:14
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelZombieCrawler extends ModelBase
{
	// fields
	ModelRenderer os_3;
	ModelRenderer os_2;
	ModelRenderer os_1;
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer os_4;
	ModelRenderer leftarm;

	public ModelZombieCrawler()
	{
		textureWidth = 64;
		textureHeight = 32;

		os_3 = new ModelRenderer(this, 0, 22);
		os_3.addBox(0F, 0F, 0F, 1, 2, 1);
		os_3.setRotationPoint(2F, 21.5F, 10F);
		os_3.setTextureSize(128, 64);
		os_3.mirror = true;
		setRotation(os_3, -0.3141593F, 0F, 0F);
		os_2 = new ModelRenderer(this, 0, 20);
		os_2.addBox(0F, 0F, 0F, 4, 1, 1);
		os_2.setRotationPoint(-2F, 21.5F, 10F);
		os_2.setTextureSize(128, 64);
		os_2.mirror = true;
		setRotation(os_2, -0.3141593F, 0F, 0F);
		os_1 = new ModelRenderer(this, 0, 16);
		os_1.addBox(0F, 0F, 0F, 1, 1, 3);
		os_1.setRotationPoint(-0.5F, 21F, 9F);
		os_1.setTextureSize(128, 64);
		os_1.mirror = true;
		setRotation(os_1, -0.3490659F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, 20F, -1F);
		head.setTextureSize(128, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 16, 16);
		body.addBox(-4F, 0F, -2F, 8, 10, 4);
		body.setRotationPoint(0F, 18F, 0F);
		body.setTextureSize(128, 64);
		body.mirror = true;
		setRotation(body, 1.115358F, 0F, 0F);
		rightarm = new ModelRenderer(this, 40, 16);
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
		rightarm.setRotationPoint(-5F, 19F, 1F);
		rightarm.setTextureSize(128, 64);
		rightarm.mirror = true;
		setRotation(rightarm, -1.22173F, 0F, 0F);
		os_4 = new ModelRenderer(this, 0, 25);
		os_4.addBox(0F, 0F, 0F, 1, 2, 1);
		os_4.setRotationPoint(-3F, 21.5F, 10F);
		os_4.setTextureSize(128, 64);
		os_4.mirror = true;
		setRotation(os_4, -0.3141593F, 0F, 0F);
		leftarm = new ModelRenderer(this, 40, 16);
		leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
		leftarm.setRotationPoint(5F, 19F, 1F);
		leftarm.setTextureSize(128, 64);
		leftarm.mirror = true;
		setRotation(leftarm, -1.22173F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		os_3.render(f5);
		os_2.render(f5);
		os_1.render(f5);
		head.render(f5);
		body.render(f5);
		rightarm.render(f5);
		os_4.render(f5);
		leftarm.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
}

